FULL_CONTENT = 'div[class="card-wrap"]'
EXPAND_TEXT = '展开全文'
COLLAPSE_TEXT = '收起全文'
CONTENT = 'p[class="txt"][node-type="feed_list_content"]'
EXPANDED_CONTENT = 'p[class="txt"][node-type="feed_list_content_full"]'
URL = 'p[class="from"] > a'
MEDIA = 'div[node-type="feed_list_media_prev"]'
VIDEO = 'div[class="media media-video-a"]'
REBLOG = 'div[class="card-comment"]'
REBLOG_2 = 'div[class="media media-article-a"]'
LINK = '网页链接'

