FULL_CONTENT_SELECTOR = 'div[class="card-wrap"]'
EXPAND_TEXT_SELECTOR = '展开全文'
COLLAPSE_TEXT_SELECTOR = '收起全文'
CONTENT_SELECTOR = 'p[class="txt"][node-type="feed_list_content"]'
EXPANDED_CONTENT_SELECTOR = 'p[class="txt"][node-type="feed_list_content_full"]'
URL_SELECTOR = 'p[class="from"] > a'
MEDIA_SELECTOR = 'div[node-type="feed_list_media_prev"]'
REBLOG_SELECTOR = 'div[class="card-comment"]'
REBLOG_SELECTOR_2 = 'div[class="media media-article-a"]'
LINK_SELECTOR = '网页链接'
